msg:
    1:  La publicité a bien été ajoutée.
    2:  Votre offre de partenariat a bien été proposée. Elle va être examinée par les administrateurs. Merci de votre confiance !
    3:  L'apparence a bien été modifiée. Elle prend effet immédiatement.
    4:  Le ciblage a bien été modifié. Il prend effet immédiatement.
    5:  La campagne a bien été supprimée.
    6:  Cette publicité n'existe pas.
    7:  Les clics ont bien été remis à zéro.
    8:  Cette date n'est pas valide.
    9:  La publicité a bien été validée.
    10: La publicité a bien été refusée.
    11: Les affichages ont bien été remis à zéro.
    12: Cette campagne n'existe pas.
    13: Cette publicité n'est pas en attente de validation.
    14: Ce rapport n'existe pas.
    15: Ce membre n'existe pas.
    16: Le créateur de la campagne a bien été modifié.